languageCode = "en"
languageName = "English"
weight = 1

title = "mdjiyehoue.eng"
# copyright = "Copy, _right?_ :thinking_face:"


[params]
rtl = false
isoCode = "en"
displayName = "EN"
dateFormat = "January 2, 2006"
description = "A blog by Manuel D."
# mainSections = ["section1", "section2"]

[params.author]
bio = "Engineering 🛠️ ~ Scalable Infrastructures, Cloud Computing & Machine Learning 🧮"
name = "Manuel D."
image = "img/author.jpg"
headline = "Engineering 🛠️ ~ Scalable Infrastructures, Cloud Computing & Machine Learning 🧮"
links = [
    { youtube = "https://www.youtube.com/@engwmanuel" },
    { github = "https://github.com/KuessiAnsan" },
#    { twitter = "https://twitter.com/megaconfidence" },
    { linkedin = "https://www.linkedin.com/in/manuel-d-435b16355/" },
]
